-- Unified Customer Firebase Push Notifications — Step 1 Foundation + Manual Sending
-- Supports authenticated Tenant Mode and ARS Guest Mode device tokens.
-- Firebase service account credentials must stay outside webroot; this migration stores no secrets.

CREATE TABLE IF NOT EXISTS `customer_device_tokens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `user_type` ENUM('tenant','guest') NOT NULL,
  `tenant_portal_user_id` INT(11) DEFAULT NULL,
  `tenant_id` INT(11) DEFAULT NULL,
  `lease_id` INT(11) DEFAULT NULL,
  `guest_portal_user_id` INT(11) DEFAULT NULL,
  `guest_id` INT(11) DEFAULT NULL,
  `booking_id` INT(11) DEFAULT NULL,
  `platform` ENUM('android','ios','web','unknown') NOT NULL DEFAULT 'unknown',
  `device_id` VARCHAR(150) DEFAULT NULL,
  `fcm_token` TEXT NOT NULL,
  `token_hash` CHAR(64) NOT NULL,
  `app_version` VARCHAR(50) DEFAULT NULL,
  `device_name` VARCHAR(150) DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_seen_at` DATETIME DEFAULT NULL,
  `invalidated_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_customer_device_token_hash` (`token_hash`),
  KEY `idx_customer_tokens_scope` (`company_id`, `user_type`, `is_active`),
  KEY `idx_customer_tokens_tenant` (`tenant_portal_user_id`, `tenant_id`, `lease_id`),
  KEY `idx_customer_tokens_guest` (`guest_portal_user_id`, `guest_id`, `booking_id`),
  KEY `idx_customer_tokens_device` (`user_type`, `device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_notification_batches` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `user_type_scope` ENUM('tenant','guest','mixed') NOT NULL,
  `target_scope` VARCHAR(50) NOT NULL,
  `target_label` VARCHAR(255) DEFAULT NULL,
  `action_type` VARCHAR(50) NOT NULL DEFAULT 'general',
  `title` VARCHAR(200) NOT NULL,
  `message` VARCHAR(500) DEFAULT NULL,
  `recipient_count` INT(11) NOT NULL DEFAULT 0,
  `token_count` INT(11) NOT NULL DEFAULT 0,
  `sent_count` INT(11) NOT NULL DEFAULT 0,
  `failed_count` INT(11) NOT NULL DEFAULT 0,
  `invalid_token_count` INT(11) NOT NULL DEFAULT 0,
  `created_by` INT(11) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_customer_batches_company` (`company_id`, `created_at`),
  KEY `idx_customer_batches_scope` (`user_type_scope`, `target_scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_push_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `user_type` ENUM('tenant','guest') NOT NULL,
  `batch_id` INT(11) DEFAULT NULL,
  `tenant_notification_id` INT(11) DEFAULT NULL,
  `guest_notification_id` INT(11) DEFAULT NULL,
  `device_token_id` INT(11) DEFAULT NULL,
  `tenant_portal_user_id` INT(11) DEFAULT NULL,
  `tenant_id` INT(11) DEFAULT NULL,
  `lease_id` INT(11) DEFAULT NULL,
  `guest_portal_user_id` INT(11) DEFAULT NULL,
  `guest_id` INT(11) DEFAULT NULL,
  `booking_id` INT(11) DEFAULT NULL,
  `target_scope` VARCHAR(50) NOT NULL DEFAULT 'manual',
  `action_type` VARCHAR(50) NOT NULL DEFAULT 'general',
  `status` ENUM('pending','sent','failed','invalid_token','skipped') NOT NULL DEFAULT 'pending',
  `firebase_message_id` VARCHAR(255) DEFAULT NULL,
  `error_code` VARCHAR(100) DEFAULT NULL,
  `error_message` TEXT DEFAULT NULL,
  `created_by` INT(11) DEFAULT NULL,
  `sent_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_customer_push_company` (`company_id`, `created_at`),
  KEY `idx_customer_push_batch` (`batch_id`),
  KEY `idx_customer_push_token` (`device_token_id`),
  KEY `idx_customer_push_status` (`status`),
  KEY `idx_customer_push_tenant` (`tenant_notification_id`, `tenant_id`),
  KEY `idx_customer_push_guest` (`guest_notification_id`, `guest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ars_guest_notifications`
  MODIFY `event_type` ENUM(
    'booking_created',
    'booking_confirmed',
    'payment_succeeded',
    'payment_failed',
    'booking_cancelled',
    'booking_expired',
    'reminder_checkin',
    'reminder_checkout',
    'request_approved',
    'request_rejected',
    'request_cancelled',
    'deposit_required',
    'deposit_received',
    'deposit_refunded',
    'deposit_cash_selected',
    'manual_general',
    'manual_booking',
    'manual_payment',
    'manual_lifecycle_request',
    'manual_document',
    'manual_receipt',
    'manual_checkin',
    'manual_checkout'
  ) NOT NULL;
