-- ============================================================================
-- Real Estate Accounting Transformation - Phase 2 Obligation Engine
-- ----------------------------------------------------------------------------
-- Purpose:
--   Add idempotency/support metadata for generated obligations.
--
-- Safety:
--   - Additive only.
--   - No historical conversion.
--   - No invoice generation.
--   - No journal posting.
--   - No payment/allocation/cheque changes.
--   - Existing re_obligations rows are not deleted or reposted.
-- ============================================================================

ALTER TABLE `re_obligations`
    ADD COLUMN IF NOT EXISTS `obligation_key` VARCHAR(190) DEFAULT NULL
        COMMENT 'Stable idempotency key generated by the obligation engine' AFTER `source_id`,
    ADD COLUMN IF NOT EXISTS `engine_version` VARCHAR(30) DEFAULT NULL
        COMMENT 'Obligation engine version that generated/updated this row' AFTER `notes`,
    ADD COLUMN IF NOT EXISTS `generated_at` DATETIME DEFAULT NULL
        COMMENT 'When this row was generated by the obligation engine' AFTER `engine_version`,
    ADD COLUMN IF NOT EXISTS `generated_by` INT(11) DEFAULT NULL
        COMMENT 'User id that triggered obligation generation' AFTER `generated_at`;

CREATE UNIQUE INDEX IF NOT EXISTS `uq_re_obligations_company_key`
    ON `re_obligations` (`company_id`, `obligation_key`);

CREATE INDEX IF NOT EXISTS `idx_re_obligations_engine`
    ON `re_obligations` (`company_id`, `engine_version`, `generated_at`);

