-- ============================================================================
-- Real Estate Accounting Transformation - Phase 3 Invoice Engine
-- ----------------------------------------------------------------------------
-- Purpose:
--   Add idempotency and obligation linkage fields for Invoice Mode invoices.
--
-- Safety:
--   - Additive only.
--   - No historical invoice generation.
--   - No automatic conversion.
--   - No receipt/payment/cheque changes.
--   - No journal posting.
--   - Existing invoices and invoice lines are not backfilled or modified.
-- ============================================================================

ALTER TABLE `re_invoices`
    ADD COLUMN IF NOT EXISTS `invoice_key` VARCHAR(190) DEFAULT NULL
        COMMENT 'Stable idempotency key generated by the Phase 3 invoice engine' AFTER `invoice_number`,
    ADD COLUMN IF NOT EXISTS `invoice_source` VARCHAR(50) DEFAULT NULL
        COMMENT 'Source engine/process that created this invoice' AFTER `invoice_key`,
    ADD COLUMN IF NOT EXISTS `engine_version` VARCHAR(30) DEFAULT NULL
        COMMENT 'Invoice engine version that generated this invoice' AFTER `notes`,
    ADD COLUMN IF NOT EXISTS `generated_at` DATETIME DEFAULT NULL
        COMMENT 'When this invoice was generated by the invoice engine' AFTER `engine_version`,
    ADD COLUMN IF NOT EXISTS `generated_by` INT(11) DEFAULT NULL
        COMMENT 'User id that triggered invoice generation' AFTER `generated_at`;

CREATE UNIQUE INDEX IF NOT EXISTS `uq_re_invoices_company_invoice_key`
    ON `re_invoices` (`company_id`, `invoice_key`);

CREATE INDEX IF NOT EXISTS `idx_re_invoices_engine`
    ON `re_invoices` (`company_id`, `invoice_source`, `engine_version`, `generated_at`);

ALTER TABLE `re_invoice_items`
    ADD COLUMN IF NOT EXISTS `obligation_id` BIGINT UNSIGNED DEFAULT NULL
        COMMENT 'Source re_obligations.id for Phase 3 generated invoice lines' AFTER `billing_item_id`;

CREATE UNIQUE INDEX IF NOT EXISTS `uq_re_invoice_items_obligation`
    ON `re_invoice_items` (`company_id`, `obligation_id`);

CREATE INDEX IF NOT EXISTS `idx_re_invoice_items_obligation`
    ON `re_invoice_items` (`obligation_id`);

