<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/../../includes/auth.php'; require_once __DIR__ . '/../../includes/db_connect.php'; require_once __DIR__ . '/../../includes/branding.php'; require_once __DIR__ . '/../../includes/company_helper.php'; require_once __DIR__ . '/../../includes/module_access.php'; require_once __DIR__ . '/includes/reporting_mode_helper.php';
require_login(); require_module_access($conn, MODULE_REALESTATE); $brand=getBrandSettings($conn); $companyId=current_company_id($conn)?:1; function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');} function m($n){return number_format((float)$n,2);} $counts=re_report_mode_counts($conn,$companyId); $rent=re_report_combined_rent_roll($conn,$companyId); $out=re_report_combined_outstanding($conn,$companyId,date('Y-m-d')); $collections=re_report_combined_collections($conn,$companyId,date('Y-m-01'),date('Y-m-d'));
$pageTitle='Legacy vs Invoice Mode Diagnostic'; require_once __DIR__ . '/includes/re_layout_header.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-header-label"><i class="bi bi-diagram-3"></i> Legacy vs Invoice Mode Diagnostic</div><a href="reports.php" class="btn btn-outline-secondary">Reports Center</a></div><div class="alert alert-warning">Diagnostic only. This page does not convert, recalculate, repost, or modify historical data.</div>
<div class="row g-3 mb-4"><?php foreach([['Legacy leases',$counts['legacy_total']],['Invoice Mode leases',$counts['invoice_total']],['Active Legacy',$counts['legacy_active']],['Active Invoice',$counts['invoice_active']],['Legacy with payments',$counts['legacy_with_payments']],['Invoice missing obligations',$counts['invoice_missing_obligations']],['Invoice missing candidates',$counts['invoice_missing_invoices']],['Renewals still Legacy',$counts['renewal_legacy']],['New leases still Legacy',$counts['new_legacy']]] as $c): ?><div class="col-md-3"><div class="card"><div class="card-body text-center"><div class="text-muted small"><?=h($c[0])?></div><h3><?=h($c[1])?></h3></div></div></div><?php endforeach; ?></div>
<div class="row g-3"><div class="col-md-4"><div class="card"><div class="card-header">Contracted Rent</div><div class="card-body">Legacy <?=m($rent['legacy'])?><br>Invoice <?=m($rent['invoice'])?><hr>Combined <?=m($rent['combined'])?></div></div></div><div class="col-md-4"><div class="card"><div class="card-header">Outstanding</div><div class="card-body">Legacy <?=m($out['legacy'])?><br>Invoice <?=m($out['invoice'])?><hr>Combined <?=m($out['combined'])?></div></div></div><div class="col-md-4"><div class="card"><div class="card-header">Collections This Month</div><div class="card-body">Legacy <?=m($collections['legacy'])?><br>Invoice <?=m($collections['invoice'])?><hr>Combined <?=m($collections['combined'])?></div></div></div></div>
<?php require_once __DIR__ . '/includes/re_layout_footer.php'; ?>
