<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/../../includes/auth.php'; require_once __DIR__ . '/../../includes/db_connect.php'; require_once __DIR__ . '/../../includes/branding.php'; require_once __DIR__ . '/../../includes/company_helper.php'; require_once __DIR__ . '/../../includes/module_access.php'; require_once __DIR__ . '/includes/reporting_mode_helper.php';
require_login(); require_module_access($conn, MODULE_REALESTATE); $brand=getBrandSettings($conn); $companyId=current_company_id($conn)?:1; function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');} function m($n){return number_format((float)$n,2);} $from=$_GET['date_from']??date('Y-m-01'); $to=$_GET['date_to']??date('Y-m-d');
$collections=re_report_combined_collections($conn,$companyId,$from,$to); $invoiced=0; $legacyContract=0; $glIncome=0; $serviceIncome=0; $penalties=0;
try{$st=$conn->prepare("SELECT COALESCE(SUM(i.subtotal),0) FROM re_invoices i JOIN re_leases l ON l.id=i.lease_id AND l.company_id=i.company_id WHERE i.company_id=? AND i.invoice_date BETWEEN ? AND ? AND i.status<>'cancelled'");$st->execute([$companyId,$from,$to]);$invoiced=(float)$st->fetchColumn();}catch(Throwable $e){}
try{$st=$conn->prepare("SELECT COALESCE(SUM(annual_rent/12),0) FROM re_leases WHERE company_id=? AND COALESCE(accounting_mode,'legacy')='legacy' AND status='active'");$st->execute([$companyId]);$legacyContract=(float)$st->fetchColumn();}catch(Throwable $e){}
try{$st=$conn->prepare("SELECT coa.account_code, coa.account_name, COALESCE(SUM(gl.credit_amount-gl.debit_amount),0) amt FROM re_general_ledger gl JOIN re_chart_of_accounts coa ON coa.id=gl.account_id WHERE gl.company_id=? AND gl.entry_date BETWEEN ? AND ? AND coa.account_type='Income' GROUP BY coa.id ORDER BY coa.account_code");$st->execute([$companyId,$from,$to]);$incomeRows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($incomeRows as $r){$glIncome+=(float)$r['amt']; if(stripos($r['account_name'],'service')!==false)$serviceIncome+=(float)$r['amt']; if(stripos($r['account_name'],'penalt')!==false)$penalties+=(float)$r['amt'];}}catch(Throwable $e){$incomeRows=[];}
$pageTitle='Income Summary'; require_once __DIR__ . '/includes/re_layout_header.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-header-label"><i class="bi bi-graph-up-arrow"></i> Income Summary</div><a href="reports.php" class="btn btn-outline-secondary">Reports Center</a></div><div class="alert alert-info">Combined report: Legacy contracted rent is operational; Invoice Mode invoiced rent and GL recognized revenue are accounting sources. Security deposits are excluded from income.</div>
<form class="card card-round mb-4"><div class="card-body row g-3"><div class="col-md-4"><input type="date" name="date_from" class="form-control" value="<?=h($from)?>"></div><div class="col-md-4"><input type="date" name="date_to" class="form-control" value="<?=h($to)?>"></div><div class="col-md-4"><button class="btn btn-primary w-100">Load</button></div></div></form>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Legacy Contracted Monthly Rent</div><h4><?=m($legacyContract)?></h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Invoice Mode Invoiced Rent/Charges</div><h4><?=m($invoiced)?></h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">Collected Cash</div><h4><?=m($collections['combined'])?></h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted">GL Income Recognized</div><h4><?=m($glIncome)?></h4></div></div></div></div>
<div class="card card-round"><div class="card-header">GL Income Breakdown</div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Account</th><th class="text-end">Amount</th></tr></thead><tbody><?php foreach($incomeRows as $r): ?><tr><td><?=h($r['account_code'].' '.$r['account_name'])?></td><td class="text-end"><?=m($r['amt'])?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php require_once __DIR__ . '/includes/re_layout_footer.php'; ?>
