<?php
/**
 * Data-safe schema sync (additive only) — shared library + CLI runner.
 *
 * Compares a SOURCE database (your up-to-date schema) against a TARGET database
 * (e.g. live) and produces the SQL needed to bring TARGET's STRUCTURE in line:
 *   - CREATE TABLE      for tables that exist in source but not in target
 *   - ALTER ... ADD     for columns that exist in source but not in target
 *   - ALTER ... ADD KEY for indexes that exist in source but not in target
 *
 * It NEVER drops a table, column or index, and NEVER modifies row data, so it
 * cannot delete or overwrite live data. Column TYPE differences on existing
 * columns are only REPORTED (not auto-changed) unless --modify / $emitModify.
 *
 * This file is safe to include as a library (it only auto-runs under CLI).
 * For a browser-based runner on hosts without SSH, see tools/db_schema_sync_web.php.
 *
 * CLI USAGE (dry-run prints SQL, writes a .sql file, applies nothing):
 *   php tools/db_schema_sync.php \
 *       --src-host=127.0.0.1 --src-db=schema_src --src-user=U --src-pass=P \
 *       --dst-host=127.0.0.1 --dst-db=LIVE      --dst-user=U --dst-pass=P
 *   Add --apply to execute on TARGET. Add --modify to also emit MODIFY for type diffs.
 */

// ---------------------------------------------------------------------------
// Library functions
// ---------------------------------------------------------------------------

function schema_sync_connect(string $host, string $db, string $user, string $pass): PDO {
    return new PDO("mysql:host={$host};dbname={$db};charset=utf8mb4", $user, $pass, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
}

function schema_sync_tables(PDO $c, string $db): array {
    $s = $c->prepare("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_NAME");
    $s->execute([$db]);
    return $s->fetchAll(PDO::FETCH_COLUMN);
}

function schema_sync_columns(PDO $c, string $db, string $table): array {
    $s = $c->prepare("SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, ORDINAL_POSITION
                      FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? ORDER BY ORDINAL_POSITION");
    $s->execute([$db, $table]);
    $out = [];
    foreach ($s->fetchAll() as $r) { $out[$r['COLUMN_NAME']] = $r; }
    return $out;
}

function schema_sync_index_names(PDO $c, string $db, string $table): array {
    $s = $c->prepare("SELECT DISTINCT INDEX_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?");
    $s->execute([$db, $table]);
    return $s->fetchAll(PDO::FETCH_COLUMN);
}

function schema_sync_show_create(PDO $c, string $table): string {
    $s = $c->query("SHOW CREATE TABLE `" . str_replace('`', '', $table) . "`");
    $row = $s->fetch(PDO::FETCH_ASSOC);
    return $row['Create Table'] ?? ($row['Create View'] ?? '');
}

/** Parse a SHOW CREATE TABLE body into ['cols'=>[name=>defLine], 'keys'=>[keyname=>defLine]]. */
function schema_sync_parse_create(string $ddl): array {
    $cols = []; $keys = [];
    foreach (preg_split('/\r?\n/', $ddl) as $line) {
        $t = trim(rtrim(trim($line), ','));
        if ($t === '' || stripos($t, 'CREATE TABLE') === 0 || $t[0] === ')') continue;
        if (preg_match('/^`([^`]+)`\s+(.+)$/', $t, $m) && stripos($t, 'PRIMARY KEY') !== 0) {
            $cols[$m[1]] = $t;
        } elseif (preg_match('/^(PRIMARY KEY|UNIQUE KEY|KEY|FULLTEXT KEY|SPATIAL KEY|CONSTRAINT)\b/i', $t)) {
            if (preg_match('/KEY\s+`([^`]+)`/i', $t, $km)) {
                $keys[$km[1]] = $t;
            } elseif (stripos($t, 'PRIMARY KEY') === 0) {
                $keys['PRIMARY'] = $t;
            }
        }
    }
    return ['cols' => $cols, 'keys' => $keys];
}

/**
 * Build the additive sync plan.
 * @return array{sql:string, ddl:string[], report:array, type_diffs:string[]}
 */
function schema_sync_generate(PDO $src, string $srcDb, PDO $dst, string $dstDb, bool $emitModify = false): array {
    $srcTables = schema_sync_tables($src, $srcDb);
    $dstSet = array_flip(schema_sync_tables($dst, $dstDb));

    $sql = [];
    $ddl = [];
    $typeDiffs = [];
    $report = ['new_tables' => 0, 'new_columns' => 0, 'new_indexes' => 0, 'type_diffs' => 0];

    $sql[] = "-- Generated by tools/db_schema_sync.php on " . date('Y-m-d H:i:s');
    $sql[] = "-- SOURCE db: {$srcDb}   TARGET db: {$dstDb}";
    $sql[] = "-- Additive only: CREATE TABLE / ADD COLUMN / ADD KEY. No drops, no data changes.";
    $sql[] = "SET FOREIGN_KEY_CHECKS = 0;";
    $sql[] = "";

    foreach ($srcTables as $t) {
        if (!isset($dstSet[$t])) {
            $create = preg_replace('/^CREATE TABLE /i', 'CREATE TABLE IF NOT EXISTS ', trim(schema_sync_show_create($src, $t)));
            $sql[] = "-- [NEW TABLE] {$t}";
            $sql[] = rtrim($create, ';') . ";";
            $sql[] = "";
            $ddl[] = rtrim($create, ';');
            $report['new_tables']++;
            continue;
        }

        $srcParsed = schema_sync_parse_create(schema_sync_show_create($src, $t));
        $srcCols   = schema_sync_columns($src, $srcDb, $t);
        $dstCols   = schema_sync_columns($dst, $dstDb, $t);

        $alterAdds = [];
        $prev = null;
        foreach (array_keys($srcCols) as $colName) {
            if (!isset($dstCols[$colName])) {
                $defLine = $srcParsed['cols'][$colName] ?? null;
                if ($defLine) {
                    $after = $prev ? " AFTER `{$prev}`" : " FIRST";
                    $alterAdds[] = "ADD COLUMN {$defLine}{$after}";
                    $report['new_columns']++;
                }
            } else {
                if ($srcCols[$colName]['COLUMN_TYPE'] !== $dstCols[$colName]['COLUMN_TYPE']
                    || $srcCols[$colName]['IS_NULLABLE'] !== $dstCols[$colName]['IS_NULLABLE']) {
                    $report['type_diffs']++;
                    $defLine = $srcParsed['cols'][$colName] ?? null;
                    $msg = "{$t}.{$colName}: source='{$srcCols[$colName]['COLUMN_TYPE']}' null={$srcCols[$colName]['IS_NULLABLE']}"
                         . " | target='{$dstCols[$colName]['COLUMN_TYPE']}' null={$dstCols[$colName]['IS_NULLABLE']}";
                    $typeDiffs[] = $msg;
                    if ($emitModify && $defLine) {
                        $alterAdds[] = "MODIFY COLUMN {$defLine}";
                    } else {
                        $sql[] = "-- [TYPE DIFF] {$msg}  (use --modify to emit MODIFY)";
                    }
                }
            }
            $prev = $colName;
        }

        $dstIdx = array_flip(schema_sync_index_names($dst, $dstDb, $t));
        foreach ($srcParsed['keys'] as $keyName => $keyDef) {
            if ($keyName === 'PRIMARY') continue;
            if (!isset($dstIdx[$keyName])) {
                if (stripos($keyDef, 'CONSTRAINT') === 0 || stripos($keyDef, 'FOREIGN KEY') !== false) continue;
                $alterAdds[] = "ADD " . $keyDef;
                $report['new_indexes']++;
            }
        }

        if ($alterAdds) {
            $alterStmt = "ALTER TABLE `{$t}`\n    " . implode(",\n    ", $alterAdds);
            $sql[] = "-- [ALTER] {$t}";
            $sql[] = $alterStmt . ";";
            $sql[] = "";
            $ddl[] = $alterStmt;
        }
    }

    $sql[] = "SET FOREIGN_KEY_CHECKS = 1;";
    return ['sql' => implode("\n", $sql) . "\n", 'ddl' => $ddl, 'report' => $report, 'type_diffs' => $typeDiffs];
}

/** Execute the collected DDL statements on the target. @return array{applied:int,errors:int,messages:string[]} */
function schema_sync_apply(PDO $dst, array $ddl): array {
    $applied = 0; $errors = 0; $messages = [];
    $dst->exec("SET FOREIGN_KEY_CHECKS = 0");
    foreach ($ddl as $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '') continue;
        try {
            $dst->exec($stmt);
            $applied++;
        } catch (Throwable $e) {
            $errors++;
            $messages[] = "Failed: " . substr(preg_replace('/\s+/', ' ', $stmt), 0, 120) . "... -> " . $e->getMessage();
        }
    }
    $dst->exec("SET FOREIGN_KEY_CHECKS = 1");
    return ['applied' => $applied, 'errors' => $errors, 'messages' => $messages];
}

// ---------------------------------------------------------------------------
// CLI runner (only when executed directly from the command line)
// ---------------------------------------------------------------------------
if (PHP_SAPI === 'cli' && isset($argv) && realpath($argv[0]) === realpath(__FILE__)) {
    $opts = [];
    foreach ($argv as $arg) {
        if (preg_match('/^--([a-z\-]+)(?:=(.*))?$/', $arg, $m)) { $opts[$m[1]] = $m[2] ?? true; }
    }
    $apply      = !empty($opts['apply']);
    $emitModify = !empty($opts['modify']);
    $srcHost = $opts['src-host'] ?? '127.0.0.1';
    $srcDb   = $opts['src-db']   ?? 'datanew';
    $srcUser = $opts['src-user'] ?? 'root';
    $srcPass = $opts['src-pass'] ?? '';
    $dstHost = $opts['dst-host'] ?? '127.0.0.1';
    $dstDb   = $opts['dst-db']   ?? null;
    $dstUser = $opts['dst-user'] ?? 'root';
    $dstPass = $opts['dst-pass'] ?? '';

    if (!$dstDb) { fwrite(STDERR, "ERROR: --dst-db is required.\n"); exit(2); }

    try {
        $src = schema_sync_connect($srcHost, $srcDb, $srcUser, $srcPass);
        $dst = schema_sync_connect($dstHost, $dstDb, $dstUser, $dstPass);
    } catch (Throwable $e) {
        fwrite(STDERR, "DB connection failed: " . $e->getMessage() . "\n");
        exit(2);
    }

    $plan = schema_sync_generate($src, $srcDb, $dst, $dstDb, $emitModify);
    $outFile = dirname(__DIR__) . '/migrations/_generated_schema_sync.sql';
    @file_put_contents($outFile, $plan['sql']);
    echo $plan['sql'];

    $r = $plan['report'];
    fwrite(STDERR, "\n----------------------------------------------------------------\n");
    fwrite(STDERR, "Summary: {$r['new_tables']} new table(s), {$r['new_columns']} new column(s), {$r['new_indexes']} new index(es), {$r['type_diffs']} type diff(s).\n");
    fwrite(STDERR, "Wrote: {$outFile}\n");

    if (!$apply) {
        fwrite(STDERR, "DRY-RUN: nothing applied. Review the file, then re-run with --apply.\n");
        exit(0);
    }
    if (!$plan['ddl']) { fwrite(STDERR, "Nothing to apply — target already in sync.\n"); exit(0); }

    fwrite(STDERR, "APPLYING to {$dstDb} ...\n");
    $res = schema_sync_apply($dst, $plan['ddl']);
    foreach ($res['messages'] as $m) { fwrite(STDERR, "  ! {$m}\n"); }
    fwrite(STDERR, "Done. {$res['applied']} applied, {$res['errors']} error(s).\n");
    exit($res['errors'] ? 1 : 0);
}
