<?php
/**
 * Construction wrappers around shared erp_module_theme helpers.
 */
require_once dirname(__DIR__, 3) . '/includes/erp_module_theme.php';

function co_theme_get(PDO $conn, int $companyId): array {
    return erp_theme_get($conn, $companyId, ERP_THEME_MODULE_CONSTRUCTION);
}

function co_theme_save(PDO $conn, int $companyId, array $payload, ?int $userId): array {
    return erp_theme_save($conn, $companyId, ERP_THEME_MODULE_CONSTRUCTION, $payload, $userId);
}

function co_theme_reset(PDO $conn, int $companyId): bool {
    return erp_theme_reset($conn, $companyId, ERP_THEME_MODULE_CONSTRUCTION);
}

function co_theme_defaults(): array {
    return erp_theme_defaults(ERP_THEME_MODULE_CONSTRUCTION);
}

/**
 * Curated Construction theme templates (centralized preset definitions).
 *
 * @return list<array{
 *   id:string,name:string,description:string,mode:string,recommended?:bool,
 *   swatches:list<string>,theme:array<string,string>
 * }>
 */
function co_theme_templates(): array {
    return [
        // —— Recommended Light Themes ——
        [
            'id' => 'cloud_blue',
            'name' => 'Cloud Blue',
            'description' => 'Clean professional blue theme with soft grey-blue surfaces and a small warm construction accent.',
            'mode' => 'light',
            'recommended' => true,
            'swatches' => ['#F1F5F9', '#FFFFFF', '#2563EB'],
            'theme' => co_theme_defaults(),
        ],
        [
            'id' => 'sage_stone',
            'name' => 'Sage & Stone',
            'description' => 'A calm natural theme using soft sage, stone grey, and green accents.',
            'mode' => 'light',
            'swatches' => ['#EFF3F0', '#FFFFFF', '#2F7D6D'],
            'theme' => [
                'primary' => '#2F7D6D',
                'primary_hover' => '#25685B',
                'secondary' => '#78716C',
                'accent' => '#D4A72C',
                'button_primary' => '#2F7D6D',
                'sidebar_bg' => '#F5F7F4',
                'sidebar_text' => '#34413D',
                'sidebar_active' => '#DDEDE7',
                'page_bg' => '#EFF3F0',
                'card_bg' => '#FFFFFF',
                'heading' => '#1F2933',
                'body_text' => '#3F4A46',
                'muted_text' => '#718078',
                'border' => '#D8E0DB',
                'success' => '#16875B',
                'warning' => '#C98212',
                'danger' => '#D34A4A',
                'info' => '#3B82A0',
                'link' => '#267464',
                'chart_1' => '#2F7D6D',
                'chart_2' => '#D4A72C',
                'chart_3' => '#4F86C6',
                'chart_4' => '#A06CD5',
                'chart_5' => '#E07A5F',
                'border_radius' => '10',
                'shadow_intensity' => 'low',
            ],
        ],
        [
            'id' => 'sand_terracotta',
            'name' => 'Sand & Terracotta',
            'description' => 'Warm construction-inspired theme using sand, terracotta, and muted earth tones.',
            'mode' => 'light',
            'swatches' => ['#F8F3ED', '#FFFFFF', '#C65D32'],
            'theme' => [
                'primary' => '#C65D32',
                'primary_hover' => '#A94D2A',
                'secondary' => '#7C6F64',
                'accent' => '#D69E2E',
                'button_primary' => '#C65D32',
                'sidebar_bg' => '#FFF9F3',
                'sidebar_text' => '#574A42',
                'sidebar_active' => '#FCE5D9',
                'page_bg' => '#F8F3ED',
                'card_bg' => '#FFFFFF',
                'heading' => '#332722',
                'body_text' => '#584A43',
                'muted_text' => '#85756C',
                'border' => '#E6D9CF',
                'success' => '#388E5A',
                'warning' => '#D68A13',
                'danger' => '#CF4A4A',
                'info' => '#3983A8',
                'link' => '#B5522D',
                'chart_1' => '#C65D32',
                'chart_2' => '#D69E2E',
                'chart_3' => '#3F88C5',
                'chart_4' => '#5B9279',
                'chart_5' => '#9B5DE5',
                'border_radius' => '10',
                'shadow_intensity' => 'low',
            ],
        ],
        [
            'id' => 'sky_mint',
            'name' => 'Sky & Mint',
            'description' => 'Fresh modern light theme combining clean blue and mint-green accents.',
            'mode' => 'light',
            'swatches' => ['#EEF6F8', '#FFFFFF', '#0F7CBF'],
            'theme' => [
                'primary' => '#0F7CBF',
                'primary_hover' => '#0B669E',
                'secondary' => '#6B7C8F',
                'accent' => '#14B8A6',
                'button_primary' => '#0F7CBF',
                'sidebar_bg' => '#F6FAFC',
                'sidebar_text' => '#32495B',
                'sidebar_active' => '#DDF3FA',
                'page_bg' => '#EEF6F8',
                'card_bg' => '#FFFFFF',
                'heading' => '#123044',
                'body_text' => '#385366',
                'muted_text' => '#718696',
                'border' => '#D5E3E9',
                'success' => '#12A36D',
                'warning' => '#D98B15',
                'danger' => '#D94B59',
                'info' => '#2396C7',
                'link' => '#0875B7',
                'chart_1' => '#0F7CBF',
                'chart_2' => '#14B8A6',
                'chart_3' => '#F59E0B',
                'chart_4' => '#7C6FE8',
                'chart_5' => '#E85D8E',
                'border_radius' => '12',
                'shadow_intensity' => 'low',
            ],
        ],
        [
            'id' => 'lavender_slate',
            'name' => 'Lavender Slate',
            'description' => 'An elegant modern theme with soft lavender, slate, and restrained violet accents.',
            'mode' => 'light',
            'swatches' => ['#F4F2F8', '#FFFFFF', '#6D5BD0'],
            'theme' => [
                'primary' => '#6D5BD0',
                'primary_hover' => '#5848B7',
                'secondary' => '#64748B',
                'accent' => '#E29B30',
                'button_primary' => '#6D5BD0',
                'sidebar_bg' => '#FAF9FD',
                'sidebar_text' => '#45405C',
                'sidebar_active' => '#EAE6FA',
                'page_bg' => '#F4F2F8',
                'card_bg' => '#FFFFFF',
                'heading' => '#25213B',
                'body_text' => '#4B4760',
                'muted_text' => '#77728B',
                'border' => '#DDD9E8',
                'success' => '#27956A',
                'warning' => '#D28A17',
                'danger' => '#D54E61',
                'info' => '#338BB8',
                'link' => '#6250C5',
                'chart_1' => '#6D5BD0',
                'chart_2' => '#2BAE9B',
                'chart_3' => '#E29B30',
                'chart_4' => '#3D82C4',
                'chart_5' => '#D65B9A',
                'border_radius' => '12',
                'shadow_intensity' => 'low',
            ],
        ],
        [
            'id' => 'clean_corporate',
            'name' => 'Clean Corporate',
            'description' => 'Neutral and highly readable professional theme for accounting, reports, tables, and daily administration.',
            'mode' => 'light',
            'swatches' => ['#F2F4F7', '#FFFFFF', '#345995'],
            'theme' => [
                'primary' => '#345995',
                'primary_hover' => '#29497D',
                'secondary' => '#6B7280',
                'accent' => '#D99A24',
                'button_primary' => '#345995',
                'sidebar_bg' => '#F7F8FA',
                'sidebar_text' => '#374151',
                'sidebar_active' => '#E2EAF5',
                'page_bg' => '#F2F4F7',
                'card_bg' => '#FFFFFF',
                'heading' => '#172033',
                'body_text' => '#374151',
                'muted_text' => '#737B89',
                'border' => '#D9DEE7',
                'success' => '#1B8F5A',
                'warning' => '#CF8617',
                'danger' => '#CC4655',
                'info' => '#3285AD',
                'link' => '#345995',
                'chart_1' => '#345995',
                'chart_2' => '#28A286',
                'chart_3' => '#D99A24',
                'chart_4' => '#805EAE',
                'chart_5' => '#D65A78',
                'border_radius' => '8',
                'shadow_intensity' => 'low',
            ],
        ],
        // Legacy light presets (still available)
        [
            'id' => 'light_gold',
            'name' => 'Light Gold',
            'description' => 'Clean light theme — white cards, soft grey page, gold brand accents.',
            'mode' => 'light',
            'swatches' => ['#f8fafc', '#ffffff', '#d4af37'],
            'theme' => [
                'primary' => '#d4af37',
                'primary_hover' => '#c9a227',
                'secondary' => '#64748b',
                'accent' => '#d4af37',
                'button_primary' => '#d4af37',
                'sidebar_bg' => '#ffffff',
                'sidebar_text' => '#334155',
                'sidebar_active' => '#FEF3C7',
                'page_bg' => '#f1f5f9',
                'card_bg' => '#ffffff',
                'heading' => '#0f172a',
                'body_text' => '#1e293b',
                'muted_text' => '#64748b',
                'border' => '#E2E8F0',
                'success' => '#059669',
                'warning' => '#d97706',
                'danger' => '#dc2626',
                'info' => '#0284c7',
                'link' => '#a16207',
                'chart_1' => '#d4af37',
                'chart_2' => '#059669',
                'chart_3' => '#0284c7',
                'chart_4' => '#dc2626',
                'chart_5' => '#d97706',
                'border_radius' => '12',
                'shadow_intensity' => 'low',
            ],
        ],
        [
            'id' => 'sand_bronze',
            'name' => 'Sand & Bronze',
            'description' => 'Warm light surfaces with bronze/gold highlights.',
            'mode' => 'light',
            'swatches' => ['#faf6f0', '#ffffff', '#b45309'],
            'theme' => [
                'primary' => '#b45309',
                'primary_hover' => '#92400e',
                'secondary' => '#78716c',
                'accent' => '#ca8a04',
                'button_primary' => '#b45309',
                'sidebar_bg' => '#fffbeb',
                'sidebar_text' => '#44403c',
                'sidebar_active' => '#FDE68A',
                'page_bg' => '#faf6f0',
                'card_bg' => '#ffffff',
                'heading' => '#1c1917',
                'body_text' => '#292524',
                'muted_text' => '#78716c',
                'border' => '#E7E5E4',
                'success' => '#15803d',
                'warning' => '#ca8a04',
                'danger' => '#b91c1c',
                'info' => '#0369a1',
                'link' => '#92400e',
                'chart_1' => '#b45309',
                'chart_2' => '#15803d',
                'chart_3' => '#0369a1',
                'chart_4' => '#b91c1c',
                'chart_5' => '#ca8a04',
                'border_radius' => '12',
                'shadow_intensity' => 'low',
            ],
        ],
        // —— Dark Themes ——
        [
            'id' => 'midnight_gold',
            'name' => 'Midnight Gold',
            'description' => 'Classic dark Construction look — navy surfaces with gold accents.',
            'mode' => 'dark',
            'swatches' => ['#0b1220', '#151e2e', '#d4af37'],
            'theme' => [
                'primary' => '#d4af37',
                'primary_hover' => '#e8c547',
                'secondary' => '#94a3b8',
                'accent' => '#d4af37',
                'button_primary' => '#d4af37',
                'sidebar_bg' => '#0f172a',
                'sidebar_text' => '#cbd5e1',
                'sidebar_active' => '#e8c547',
                'page_bg' => '#0b1220',
                'card_bg' => '#151e2e',
                'heading' => '#f1f5f9',
                'body_text' => '#f1f5f9',
                'muted_text' => '#94a3b8',
                'border' => '#d4af37',
                'success' => '#10b981',
                'warning' => '#fbbf24',
                'danger' => '#f87171',
                'info' => '#38bdf8',
                'link' => '#e8c547',
                'chart_1' => '#d4af37',
                'chart_2' => '#10b981',
                'chart_3' => '#38bdf8',
                'chart_4' => '#f87171',
                'chart_5' => '#fbbf24',
                'border_radius' => '12',
                'shadow_intensity' => 'medium',
            ],
        ],
        [
            'id' => 'ocean_slate',
            'name' => 'Ocean Slate',
            'description' => 'Cool dark slate with teal and soft gold accents.',
            'mode' => 'dark',
            'swatches' => ['#0c1524', '#132033', '#2dd4bf'],
            'theme' => [
                'primary' => '#2dd4bf',
                'primary_hover' => '#5eead4',
                'secondary' => '#94a3b8',
                'accent' => '#d4af37',
                'button_primary' => '#14b8a6',
                'sidebar_bg' => '#0c1524',
                'sidebar_text' => '#cbd5e1',
                'sidebar_active' => '#5eead4',
                'page_bg' => '#0a1220',
                'card_bg' => '#132033',
                'heading' => '#f8fafc',
                'body_text' => '#e2e8f0',
                'muted_text' => '#94a3b8',
                'border' => '#2dd4bf',
                'success' => '#34d399',
                'warning' => '#fbbf24',
                'danger' => '#f87171',
                'info' => '#38bdf8',
                'link' => '#5eead4',
                'chart_1' => '#2dd4bf',
                'chart_2' => '#38bdf8',
                'chart_3' => '#d4af37',
                'chart_4' => '#f87171',
                'chart_5' => '#a78bfa',
                'border_radius' => '12',
                'shadow_intensity' => 'medium',
            ],
        ],
        [
            'id' => 'graphite_amber',
            'name' => 'Graphite Amber',
            'description' => 'Charcoal UI with amber gold — high-contrast dark alternative.',
            'mode' => 'dark',
            'swatches' => ['#111111', '#1a1a1a', '#f59e0b'],
            'theme' => [
                'primary' => '#f59e0b',
                'primary_hover' => '#fbbf24',
                'secondary' => '#a3a3a3',
                'accent' => '#f59e0b',
                'button_primary' => '#f59e0b',
                'sidebar_bg' => '#0a0a0a',
                'sidebar_text' => '#d4d4d4',
                'sidebar_active' => '#fbbf24',
                'page_bg' => '#111111',
                'card_bg' => '#1a1a1a',
                'heading' => '#fafafa',
                'body_text' => '#e5e5e5',
                'muted_text' => '#a3a3a3',
                'border' => '#f59e0b',
                'success' => '#22c55e',
                'warning' => '#fbbf24',
                'danger' => '#ef4444',
                'info' => '#38bdf8',
                'link' => '#fbbf24',
                'chart_1' => '#f59e0b',
                'chart_2' => '#22c55e',
                'chart_3' => '#38bdf8',
                'chart_4' => '#ef4444',
                'chart_5' => '#a78bfa',
                'border_radius' => '10',
                'shadow_intensity' => 'high',
            ],
        ],
    ];
}

/** @return list<array> */
function co_theme_templates_by_mode(string $mode): array {
    $mode = strtolower($mode) === 'dark' ? 'dark' : 'light';
    return array_values(array_filter(
        co_theme_templates(),
        static fn(array $tpl): bool => ($tpl['mode'] ?? 'light') === $mode
    ));
}

/** @return array<string,string>|null */
function co_theme_template_by_id(string $id): ?array {
    foreach (co_theme_templates() as $tpl) {
        if (($tpl['id'] ?? '') === $id) {
            return $tpl['theme'];
        }
    }
    return null;
}
