<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/../../../includes/auth.php'; require_once __DIR__ . '/../../../includes/db_connect.php'; require_once __DIR__ . '/../../../includes/branding.php'; require_once __DIR__ . '/../../../includes/company_helper.php'; require_once __DIR__ . '/../../../includes/module_access.php'; require_once __DIR__ . '/../../../includes/rbac_department.php'; require_once __DIR__ . '/../includes/reporting_mode_helper.php';
require_login(); if(!has_department_access(MODULE_REALESTATE, DEPT_REALESTATE_FINANCIAL,$conn)){require_module_access($conn,MODULE_REALESTATE);} $brand=getBrandSettings($conn); $companyId=current_company_id($conn)?:1; function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$sections=[];
$queries=[
'Invoices without journal'=>"SELECT i.id,i.invoice_number,i.total_amount FROM re_invoices i WHERE i.company_id=? AND i.status<>'cancelled' AND NOT EXISTS(SELECT 1 FROM re_journal_headers j WHERE j.company_id=i.company_id AND j.reference_type='invoice' AND j.reference_id=i.id)",
'Obligations without invoice candidates'=>"SELECT o.id,o.lease_id,o.obligation_type,o.total_amount FROM re_obligations o JOIN re_leases l ON l.id=o.lease_id AND l.company_id=o.company_id WHERE o.company_id=? AND COALESCE(l.accounting_mode,'legacy')='invoice' AND o.accounting_class<>'liability' AND o.status='open' AND NOT EXISTS(SELECT 1 FROM re_invoice_candidates c WHERE c.company_id=o.company_id AND c.obligation_id=o.id)",
'Eligible candidates not issued'=>"SELECT c.id,c.lease_id,c.eligible_on FROM re_invoice_candidates c WHERE c.company_id=? AND c.status='approved' AND c.eligible_on<=CURDATE() AND c.invoice_id IS NULL",
'Receipts without allocation'=>"SELECT p.id,p.receipt_number,p.amount FROM re_payments p WHERE p.company_id=? AND COALESCE(p.accounting_mode,'legacy')='invoice' AND (p.allocation_status IS NULL OR p.allocation_status IN('unallocated','partial'))",
'Cheque cleared but no receipt'=>"SELECT c.id,c.cheque_number,c.cheque_amount FROM re_post_dated_cheques c WHERE c.company_id=? AND c.status='cleared' AND c.payment_id IS NULL",
'Bank statement unmatched'=>"SELECT id,statement_date,description,net_amount FROM re_bank_statement_lines WHERE company_id=? AND status IN('unmatched','partially_matched','investigating') LIMIT 100",
];
foreach($queries as $title=>$sql){try{$st=$conn->prepare($sql);$st->execute([$companyId]);$sections[$title]=$st->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){$sections[$title]=[['error'=>$e->getMessage()]];}}
$modeCounts=re_report_mode_counts($conn,$companyId);
$pageTitle='Accounting Exception Dashboard'; require_once __DIR__ . '/../includes/re_layout_header.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-header-label"><i class="bi bi-exclamation-triangle"></i> Accounting Exception Dashboard</div><a href="../reports.php" class="btn btn-outline-secondary">Reports Center</a></div><div class="alert alert-warning">Diagnostic only. This page does not auto-correct, repost, or modify historical data.</div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card"><div class="card-body text-center"><div class="text-muted">Legacy Active</div><h3><?= (int)$modeCounts['legacy_active'] ?></h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body text-center"><div class="text-muted">Invoice Active</div><h3><?= (int)$modeCounts['invoice_active'] ?></h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body text-center"><div class="text-muted">Missing Obligations</div><h3><?= (int)$modeCounts['invoice_missing_obligations'] ?></h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body text-center"><div class="text-muted">Missing Candidates</div><h3><?= (int)$modeCounts['invoice_missing_invoices'] ?></h3></div></div></div></div>
<?php foreach($sections as $title=>$rows): ?><div class="card card-round mb-4"><div class="card-header d-flex justify-content-between"><h6 class="mb-0"><?=h($title)?></h6><span class="badge bg-secondary"><?=count($rows)?></span></div><div class="card-body p-0"><?php if(!$rows): ?><div class="text-center text-muted py-3">None found.</div><?php else: ?><div class="table-responsive"><table class="table table-sm"><tbody><?php foreach($rows as $row): ?><tr><td><code><?=h(json_encode($row,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></code></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endforeach; ?>
<?php require_once __DIR__ . '/../includes/re_layout_footer.php'; ?>
