<?php
/** Real Estate Accounting - Combined Tenant Statement */
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/../../../includes/auth.php';
require_once __DIR__ . '/../../../includes/db_connect.php';
require_once __DIR__ . '/../../../includes/branding.php';
require_once __DIR__ . '/../../../includes/company_helper.php';
require_once __DIR__ . '/../../../includes/module_access.php';
require_once __DIR__ . '/../../../includes/rbac_department.php';

require_login();
if (!has_department_access(MODULE_REALESTATE, DEPT_REALESTATE_FINANCIAL, $conn)) require_module_access($conn, MODULE_REALESTATE);
$brand = getBrandSettings($conn); $currentCompanyId = current_company_id($conn) ?: 1;
$tenantId = !empty($_GET['tenant_id']) ? (int)$_GET['tenant_id'] : null;
$tenantSearch = trim((string)($_GET['tenant_search'] ?? ''));
$asOfDate = !empty($_GET['as_of_date']) ? $_GET['as_of_date'] : date('Y-m-d');

$where=['company_id=?','is_active=1']; $params=[$currentCompanyId];
if($tenantSearch!==''){ $where[]="(company_name LIKE ? OR CONCAT(first_name,' ',last_name) LIKE ? OR phone LIKE ? OR email LIKE ?)"; $like='%'.$tenantSearch.'%'; array_push($params,$like,$like,$like,$like); }
$tenants=$conn->prepare("SELECT id,first_name,last_name,company_name,tenant_type,phone,email FROM re_tenants WHERE ".implode(' AND ',$where)." ORDER BY COALESCE(NULLIF(company_name,''),last_name,first_name) LIMIT 250");
$tenants->execute($params); $allTenants=$tenants->fetchAll(PDO::FETCH_ASSOC)?:[];

$tenantInfo=null; $invoices=[]; $payments=[]; $legacyInstallments=[]; $statementRows=[]; $outstandingBalance=0; $legacyOutstanding=0; $invoiceOutstanding=0; $aging=['current'=>0,'30'=>0,'60'=>0,'90'=>0,'over90'=>0];
if($tenantId){
    $stmt=$conn->prepare("SELECT * FROM re_tenants WHERE id=? AND company_id=?"); $stmt->execute([$tenantId,$currentCompanyId]); $tenantInfo=$stmt->fetch(PDO::FETCH_ASSOC);
    if($tenantInfo){
        $stmt=$conn->prepare("SELECT i.*,l.lease_number,l.id lease_id,COALESCE(l.accounting_mode,'legacy') accounting_mode,u.unit_number,b.name building_name FROM re_invoices i JOIN re_leases l ON l.id=i.lease_id AND l.company_id=i.company_id JOIN re_units u ON u.id=l.unit_id JOIN re_buildings b ON b.id=u.building_id WHERE l.tenant_id=? AND i.company_id=? AND i.invoice_date<=? AND i.status<>'cancelled' ORDER BY i.invoice_date ASC,i.id ASC");
        $stmt->execute([$tenantId,$currentCompanyId,$asOfDate]); $invoices=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];
        foreach($invoices as $inv){ $out=(float)$inv['outstanding_amount']; $invoiceOutstanding+=$out; if($out>0){$days=(strtotime($asOfDate)-strtotime($inv['due_date']))/86400; if($days<=0)$aging['current']+=$out; elseif($days<=30)$aging['30']+=$out; elseif($days<=60)$aging['60']+=$out; elseif($days<=90)$aging['90']+=$out; else $aging['over90']+=$out;} $statementRows[]=['date'=>$inv['invoice_date'],'mode'=>$inv['accounting_mode'],'type'=>'Invoice','ref'=>$inv['invoice_number'],'lease'=>$inv['lease_number'],'unit'=>$inv['building_name'].' - '.$inv['unit_number'],'debit'=>(float)$inv['total_amount'],'credit'=>0.0,'link'=>'../billing_invoice_view.php?id='.(int)$inv['id']]; }
        $stmt=$conn->prepare("SELECT p.*,l.lease_number,l.id lease_id,COALESCE(l.accounting_mode,'legacy') accounting_mode,u.unit_number,b.name building_name,COALESCE(alloc.allocated_amount,0) allocated_amount FROM re_payments p JOIN re_leases l ON l.id=p.lease_id AND l.company_id=p.company_id JOIN re_units u ON u.id=l.unit_id JOIN re_buildings b ON b.id=u.building_id LEFT JOIN (SELECT payment_id,COALESCE(SUM(amount_allocated),0) allocated_amount FROM re_receipt_allocations GROUP BY payment_id) alloc ON alloc.payment_id=p.id WHERE l.tenant_id=? AND p.company_id=? AND p.payment_date<=? ORDER BY p.payment_date ASC,p.id ASC");
        $stmt->execute([$tenantId,$currentCompanyId,$asOfDate]); $payments=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];
        foreach($payments as $pay){ $statementRows[]=['date'=>$pay['payment_date'],'mode'=>$pay['accounting_mode']?:'legacy','type'=>($pay['accounting_mode']==='invoice'?'Receipt':'Payment'),'ref'=>$pay['receipt_number']?:($pay['reference_number']?:('PAY-'.$pay['id'])),'lease'=>$pay['lease_number'],'unit'=>$pay['building_name'].' - '.$pay['unit_number'],'debit'=>0.0,'credit'=>(float)$pay['amount'],'link'=>'../payment_view.php?id='.(int)$pay['id']]; }
        try{$stmt=$conn->prepare("SELECT li.*,l.lease_number,l.id lease_id,u.unit_number,b.name building_name,COALESCE(paid.total_paid,0) total_paid,COALESCE(pdc.cheque_number,lc.cheque_number,'') cheque_number FROM re_lease_installments li JOIN re_leases l ON l.id=li.lease_id AND l.company_id=li.company_id JOIN re_units u ON u.id=l.unit_id JOIN re_buildings b ON b.id=u.building_id LEFT JOIN (SELECT installment_id,COALESCE(SUM(amount_allocated),0) total_paid FROM re_payment_allocations GROUP BY installment_id) paid ON paid.installment_id=li.id LEFT JOIN re_post_dated_cheques pdc ON pdc.installment_id=li.id AND pdc.lease_id=li.lease_id LEFT JOIN re_lease_cheques lc ON lc.installment_id=li.id AND lc.lease_id=li.lease_id WHERE l.tenant_id=? AND li.company_id=? AND COALESCE(l.accounting_mode,'legacy')='legacy' AND li.installment_date<=? ORDER BY li.installment_date ASC");$stmt->execute([$tenantId,$currentCompanyId,$asOfDate]);$legacyInstallments=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){$legacyInstallments=[];}
        foreach($legacyInstallments as $inst){$out=max(0,(float)$inst['amount']-(float)$inst['total_paid']);$legacyOutstanding+=$out;$statementRows[]=['date'=>$inst['installment_date'],'mode'=>'legacy','type'=>'Legacy Installment','ref'=>$inst['cheque_number']?:('Installment #'.$inst['id']),'lease'=>$inst['lease_number'],'unit'=>$inst['building_name'].' - '.$inst['unit_number'],'debit'=>(float)$inst['amount'],'credit'=>0.0,'link'=>'../lease_view.php?id='.(int)$inst['lease_id']];}
        usort($statementRows,static fn($a,$b)=>strcmp($a['date'],$b['date'])); $outstandingBalance=$legacyOutstanding+$invoiceOutstanding;
    }
}
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$pageTitle='Tenant Statement'; require_once __DIR__ . '/../includes/re_layout_header.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-header-label"><i class="bi bi-person-lines-fill"></i> Tenant Statement</div><?php if($tenantId): ?><button type="button" class="btn btn-outline-secondary" onclick="window.print()">Print</button><?php endif; ?></div>
<div class="alert alert-info">Combined tenant statement. Legacy Mode rows use historical installments/payments; Invoice Mode rows use invoices, receipts and allocations.</div>
<div class="card card-round mb-4"><div class="card-body"><form method="get" class="row g-3"><div class="col-md-3"><label class="form-label">Search Tenant</label><input type="text" name="tenant_search" class="form-control" value="<?=h($tenantSearch)?>" placeholder="Name, phone, email"></div><div class="col-md-4"><label class="form-label">Tenant</label><select name="tenant_id" class="form-select" onchange="this.form.submit()"><option value="">-- Select Tenant --</option><?php foreach($allTenants as $t): ?><?php $name=$t['tenant_type']==='company'?$t['company_name']:trim($t['first_name'].' '.$t['last_name']); ?><option value="<?= (int)$t['id'] ?>" <?= $tenantId===(int)$t['id']?'selected':'' ?>><?=h($name)?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">As Of</label><input type="date" name="as_of_date" class="form-control" value="<?=h($asOfDate)?>"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Load</button></div></form></div></div>
<?php if($tenantInfo): ?><?php $tenantName=$tenantInfo['tenant_type']==='company'?$tenantInfo['company_name']:trim($tenantInfo['first_name'].' '.$tenantInfo['last_name']); ?>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card"><div class="card-body"><strong><?=h($tenantName)?></strong><br><span class="text-muted"><?=h($tenantInfo['phone']?:'-')?> · <?=h($tenantInfo['email']?:'-')?></span></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><div class="text-muted">Legacy Outstanding</div><h5><?=number_format($legacyOutstanding,2)?></h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><div class="text-muted">Invoice AR</div><h5><?=number_format($invoiceOutstanding,2)?></h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><div class="text-muted">Combined</div><h5><?=number_format($outstandingBalance,2)?></h5></div></div></div><div class="col-md-2"><div class="card"><div class="card-body"><div class="text-muted">Receipts/Payments</div><h5><?=count($payments)?></h5></div></div></div></div>
<?php if($invoiceOutstanding>0): ?><div class="card card-round mb-4"><div class="card-header">Invoice Mode Aging</div><div class="card-body"><div class="row text-center"><?php foreach(['current'=>'Current','30'=>'1-30','60'=>'31-60','90'=>'61-90','over90'=>'90+'] as $k=>$label): ?><div class="col"><div class="border rounded p-2"><div class="small text-muted"><?=$label?></div><strong><?=number_format($aging[$k],2)?></strong></div></div><?php endforeach; ?></div></div></div><?php endif; ?>
<div class="card card-round mb-4"><div class="card-header">Chronological Statement</div><div class="table-responsive"><table class="table table-sm table-hover"><thead><tr><th>Date</th><th>Mode</th><th>Type</th><th>Ref</th><th>Lease</th><th>Unit</th><th class="text-end">Debit</th><th class="text-end">Credit</th><th></th></tr></thead><tbody><?php $running=0; foreach($statementRows as $row): $running += $row['debit']-$row['credit']; ?><tr><td><?=h($row['date'])?></td><td><span class="badge bg-<?=$row['mode']==='invoice'?'primary':'secondary'?>"><?=h($row['mode'])?></span></td><td><?=h($row['type'])?></td><td><?=h($row['ref'])?></td><td><?=h($row['lease'])?></td><td><?=h($row['unit'])?></td><td class="text-end"><?=$row['debit']>0?number_format($row['debit'],2):'-'?></td><td class="text-end"><?=$row['credit']>0?number_format($row['credit'],2):'-'?></td><td><a href="<?=h($row['link'])?>" class="btn btn-sm btn-outline-primary">View</a></td></tr><?php endforeach; ?><?php if(!$statementRows): ?><tr><td colspan="9" class="text-center text-muted">No tenant statement rows found.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="row g-3"><div class="col-md-6"><div class="card"><div class="card-header">Invoice Mode Invoices</div><div class="table-responsive"><table class="table table-sm"><tbody><?php foreach($invoices as $i): ?><tr><td><a href="../billing_invoice_view.php?id=<?=$i['id']?>"><?=h($i['invoice_number'])?></a></td><td><?=h($i['lease_number'])?></td><td class="text-end"><?=number_format($i['outstanding_amount'],2)?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-md-6"><div class="card"><div class="card-header">Legacy Installments</div><div class="table-responsive"><table class="table table-sm"><tbody><?php foreach($legacyInstallments as $li): ?><tr><td><?=h($li['installment_date'])?></td><td><?=h($li['cheque_number']?:('Installment #'.$li['id']))?></td><td><?=h($li['status'])?></td><td class="text-end"><?=number_format(max(0,(float)$li['amount']-(float)$li['total_paid']),2)?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php endif; ?>
<?php require_once __DIR__ . '/../includes/re_layout_footer.php'; ?>
