<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/../../../includes/auth.php'; require_once __DIR__ . '/../../../includes/db_connect.php'; require_once __DIR__ . '/../../../includes/branding.php'; require_once __DIR__ . '/../../../includes/company_helper.php'; require_once __DIR__ . '/../../../includes/module_access.php'; require_once __DIR__ . '/../../../includes/rbac_department.php';
require_login(); if(!has_department_access(MODULE_REALESTATE, DEPT_REALESTATE_FINANCIAL,$conn)){require_module_access($conn,MODULE_REALESTATE);} $brand=getBrandSettings($conn); $companyId=current_company_id($conn)?:1; function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$sections=[];$queries=[
'Old ERP / Quick Paid expenses (not vendor bills; informational)'=>"SELECT id,expense_number,expense_date,total,status,vendor_id,paid_via FROM erp_expense_headers WHERE company_id=? AND source_module='realestate' ORDER BY expense_date DESC LIMIT 100",
'Vendor bills without GL posting'=>"SELECT vi.id,vi.invoice_number,v.vendor_name,vi.total_amount,vi.status,vi.posting_status FROM re_vendor_invoices vi JOIN re_vendors v ON v.id=vi.vendor_id AND v.company_id=vi.company_id WHERE vi.company_id=? AND COALESCE(vi.posting_status,'not_posted')<>'posted' AND vi.status NOT IN('draft','void','cancelled') LIMIT 100",
'Posted bills without vendor ledger entry'=>"SELECT vi.id,vi.invoice_number,v.vendor_name FROM re_vendor_invoices vi JOIN re_vendors v ON v.id=vi.vendor_id AND v.company_id=vi.company_id WHERE vi.company_id=? AND vi.posting_status='posted' AND NOT EXISTS(SELECT 1 FROM re_account_ledger_entries ale WHERE ale.company_id=vi.company_id AND ale.reference=vi.invoice_number) LIMIT 100",
'Payments without bill allocation'=>"SELECT vp.id,vp.payment_date,v.vendor_name,vp.amount FROM re_vendor_payments vp JOIN re_vendors v ON v.id=vp.vendor_id AND v.company_id=vp.company_id WHERE vp.company_id=? AND NOT EXISTS(SELECT 1 FROM re_vendor_payment_allocations a WHERE a.company_id=vp.company_id AND a.vendor_payment_id=vp.id) LIMIT 100",
'Input VAT bill lines vs GL Input VAT variance'=>"SELECT 'Review VAT diagnostics in VAT report' AS note",
'Vendor payments not bank reconciled'=>"SELECT vp.id,vp.payment_date,v.vendor_name,vp.amount,vp.journal_id FROM re_vendor_payments vp JOIN re_vendors v ON v.id=vp.vendor_id AND v.company_id=vp.company_id WHERE vp.company_id=? AND vp.journal_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM re_bank_reconciliation_matches m WHERE m.company_id=vp.company_id AND m.source_table='re_vendor_payments' AND m.source_id=vp.id AND m.status='confirmed') LIMIT 100",
'Vendor bills overdue'=>"SELECT vi.id,vi.invoice_number,v.vendor_name,vi.due_date,COALESCE(vi.balance_due,vi.total_amount-vi.paid_amount) balance FROM re_vendor_invoices vi JOIN re_vendors v ON v.id=vi.vendor_id AND v.company_id=vi.company_id WHERE vi.company_id=? AND vi.due_date<CURDATE() AND vi.status NOT IN('paid','void','cancelled') AND COALESCE(vi.balance_due,vi.total_amount-vi.paid_amount)>0.005 LIMIT 100",
'Duplicate bill numbers for same vendor'=>"SELECT vendor_id,invoice_number,COUNT(*) cnt FROM re_vendor_invoices WHERE company_id=? GROUP BY vendor_id,invoice_number HAVING COUNT(*)>1",
];foreach($queries as $title=>$sql){try{$st=$conn->prepare($sql);$st->execute(str_contains($sql,'?')?[$companyId]:[]);$sections[$title]=$st->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){$sections[$title]=[['error'=>$e->getMessage()]];}}
$pageTitle='Vendor/AP Diagnostics';require_once __DIR__ . '/../includes/re_layout_header.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-header-label"><i class="bi bi-clipboard-data"></i> Vendor/AP Diagnostics</div><div class="d-flex gap-2"><a href="qpe_ap_duplicate_finder.php" class="btn btn-outline-danger">QPE/AP Duplicate Finder</a><a href="vendor_bills.php" class="btn btn-outline-secondary">Vendor Bills</a></div></div><div class="alert alert-warning">Diagnostic only. This page does not migrate, repost, or modify old expenses or vendor bills. Use <a href="qpe_ap_duplicate_finder.php" class="alert-link">QPE/AP Duplicate Finder</a> to review and hard-remove Quick Paid Expenses that duplicate Vendor Bills/Payments.</div><?php foreach($sections as $title=>$rows): ?><div class="card card-round mb-4"><div class="card-header d-flex justify-content-between"><h6 class="mb-0"><?=h($title)?></h6><span class="badge bg-secondary"><?=count($rows)?></span></div><div class="card-body p-0"><?php if(!$rows): ?><div class="text-center text-muted py-3">None found.</div><?php else: ?><div class="table-responsive"><table class="table table-sm"><tbody><?php foreach($rows as $row): ?><tr><td><code><?=h(json_encode($row,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></code></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endforeach; ?><?php require_once __DIR__ . '/../includes/re_layout_footer.php'; ?>
