<?php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once __DIR__ . '/../../../includes/auth.php'; require_once __DIR__ . '/../../../includes/db_connect.php'; require_once __DIR__ . '/../../../includes/branding.php'; require_once __DIR__ . '/../../../includes/company_helper.php'; require_once __DIR__ . '/../../../includes/module_access.php'; require_once __DIR__ . '/../../../includes/rbac_department.php'; require_once __DIR__ . '/../includes/vendor_ap_helper.php';
require_login(); if(!has_department_access(MODULE_REALESTATE, DEPT_REALESTATE_FINANCIAL,$conn)){require_module_access($conn,MODULE_REALESTATE);} $brand=getBrandSettings($conn); $companyId=current_company_id($conn)?:1; $success='';$error=''; function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');} function m($n){return number_format((float)$n,2);} 
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_verify();
    $action = $_POST['action'] ?? '';
    if($action==='post_to_gl'){
        $id=(int)($_POST['vendor_invoice_id']??0);
        $r=re_ap_post_vendor_bill($conn,$companyId,$id,current_user_id());
        if(!empty($r['success']))$success='Bill posted. Journal #'.$r['journal_id']; else $error=$r['error']??'Posting failed';
    }
}
$recurringRun=re_ap_generate_due_recurring_bills($conn,$companyId,current_user_id());
if(!empty($recurringRun['errors']))error_log('Recurring vendor bill generation warning: '.implode(' | ',array_slice($recurringRun['errors'],0,3)));
$q=trim($_GET['q']??'');$status=$_GET['status']??'';$vendor=(int)($_GET['vendor_id']??0);$where=['vi.company_id=?'];$args=[$companyId]; if($q!==''){$where[]='(vi.invoice_number LIKE ? OR v.vendor_name LIKE ? OR vi.order_number LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);} if($status!==''){$where[]='vi.status=?';$args[]=$status;} if($vendor>0){$where[]='vi.vendor_id=?';$args[]=$vendor;}
$stmt=$conn->prepare("SELECT vi.*,v.vendor_name,
(SELECT COUNT(*) FROM re_vendor_bill_attachments a WHERE a.vendor_invoice_id=vi.id AND a.company_id=vi.company_id) attachment_count,
(SELECT jh.id FROM re_journal_headers jh WHERE jh.company_id=vi.company_id AND jh.reference_type='vendor_invoice' AND jh.reference_id=vi.id AND jh.is_posted=1 AND jh.is_reversed=0 ORDER BY jh.id DESC LIMIT 1) posted_journal_id,
COALESCE((SELECT SUM(l.vat_amount_linked) FROM re_vendor_advance_vat_bill_links l WHERE l.company_id=vi.company_id AND l.vendor_invoice_id=vi.id AND l.status='posted'),0) AS linked_advance_vat
FROM re_vendor_invoices vi JOIN re_vendors v ON v.id=vi.vendor_id AND v.company_id=vi.company_id WHERE ".implode(' AND ',$where)." ORDER BY vi.invoice_date DESC,vi.id DESC LIMIT 500");$stmt->execute($args);$bills=$stmt->fetchAll(PDO::FETCH_ASSOC)?:[];$vendors=$conn->prepare("SELECT id,vendor_name FROM re_vendors WHERE company_id=? AND status='active' ORDER BY vendor_name");$vendors->execute([$companyId]);$vendors=$vendors->fetchAll(PDO::FETCH_ASSOC)?:[];
$pageTitle='Vendor Bills';require_once __DIR__ . '/../includes/re_layout_header.php'; ?>
<?php if($success): ?><div class="alert alert-success"><?=h($success)?></div><?php endif; ?><?php if($error): ?><div class="alert alert-danger"><?=h($error)?></div><?php endif; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div class="page-header-label"><i class="bi bi-file-earmark-text"></i> Vendor Bills</div><div><a href="bill_entry_add.php" class="btn btn-primary">New Bill</a><a href="vendor_payment_add.php" class="btn btn-success">Payment Made</a><a href="vendor_recurring_bills.php" class="btn btn-outline-info">Recurring Bills</a><a href="ap_aging.php" class="btn btn-outline-primary">AP Aging</a><a href="vendor_ledger.php" class="btn btn-outline-secondary">Vendor Ledger</a></div></div>
<div class="card card-round mb-4"><div class="card-body"><form class="row g-2"><div class="col-md-3"><input name="q" class="form-control" value="<?=h($q)?>" placeholder="Search bill/vendor/order"></div><div class="col-md-3"><select name="vendor_id" class="form-select"><option value="0">All vendors</option><?php foreach($vendors as $v): ?><option value="<?=$v['id']?>" <?=$vendor===$v['id']?'selected':''?>><?=h($v['vendor_name'])?></option><?php endforeach; ?></select></div><div class="col-md-3"><select name="status" class="form-select"><option value="">All statuses</option><?php foreach(['draft','open','partially_paid','paid','void','pending','approved','cancelled'] as $s): ?><option value="<?=$s?>" <?=$status===$s?'selected':''?>><?=h(ucwords(str_replace('_',' ',$s)))?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
<div class="card card-round"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Bill #</th><th>Vendor</th><th>Bill Date</th><th>Due Date</th><th class="text-end">Total</th><th class="text-end">Paid</th><th class="text-end">Balance</th><th>Status</th><th>GL</th><th>Attachments</th><th>Actions</th></tr></thead><tbody><?php foreach($bills as $b): ?><?php $cashPaid=(float)($b['paid_amount']??0); $linkedVat=(float)($b['linked_advance_vat']??0); $paid=round($cashPaid+$linkedVat,2); /* balance_due is authoritative (0 is valid after linked advance VAT) */ $bal=(float)($b['balance_due']??max(0,(float)$b['total_amount']-$paid)); $postedJournalId=(int)($b['journal_id'] ?: ($b['posted_journal_id'] ?? 0)); $isPosted=(($b['posting_status']??'not_posted')==='posted'||$postedJournalId>0); ?><tr><td><strong><?=h($b['invoice_number'])?></strong><br><small><?=h($b['order_number']?:'')?></small></td><td><?=h($b['vendor_name'])?></td><td><?=h($b['invoice_date'])?></td><td><?=h($b['due_date'])?></td><td class="text-end"><?=m($b['total_amount'])?></td><td class="text-end"><?=m($paid)?><?php if($linkedVat>0.005): ?><br><small class="text-muted">incl. adv VAT <?=m($linkedVat)?></small><?php endif; ?></td><td class="text-end <?= $bal>0.005?'text-danger':'text-success' ?>"><?=m($bal)?></td><td><span class="badge bg-<?= in_array($b['status'],['paid'],true)?'success':(in_array($b['status'],['draft'],true)?'warning text-dark':($b['status']==='void'||$b['status']==='cancelled'?'secondary':'primary')) ?>"><?=h($b['status'])?></span></td><td><?php if($isPosted): ?><span class="badge bg-success">Posted</span><?php else: ?><form method="post"><?php csrf_field(); ?><input type="hidden" name="action" value="post_to_gl"><input type="hidden" name="vendor_invoice_id" value="<?=$b['id']?>"><button class="btn btn-sm btn-outline-primary">Post</button></form><?php endif; ?></td><td><?= (int)($b['attachment_count']??0) ?></td><td class="d-flex flex-wrap gap-1">
<a href="vendor_bill_view.php?id=<?=$b['id']?>" class="btn btn-sm btn-primary">View</a>
<a href="vendor_bill_edit.php?id=<?=$b['id']?>" class="btn btn-sm btn-outline-primary">Edit</a>
<?php if($isPosted&&$cashPaid<=0.005&&!in_array($b['status'],['void','cancelled','paid'],true)): ?><a href="vendor_bill_view.php?id=<?=$b['id']?>" class="btn btn-sm btn-outline-warning">Void/Amend</a><?php endif; ?>
<?php if($bal>0&&$isPosted): ?><a href="vendor_payment_add.php?vendor_id=<?=$b['vendor_id']?>&bill_id=<?=$b['id']?>" class="btn btn-sm btn-success">Pay</a><?php endif; ?>
<a href="vendor_bill_view.php?id=<?=$b['id']?>&print=1" class="btn btn-sm btn-outline-dark" target="_blank">Print</a>
<a href="vendor_recurring_bills.php?action=create&source_bill_id=<?=$b['id']?>" class="btn btn-sm btn-outline-info">Recurring</a>
<?php if($postedJournalId): ?><a href="journal_entry_view.php?id=<?=$postedJournalId?>" class="btn btn-sm btn-outline-secondary">Journal</a><?php endif; ?>
</td></tr><?php endforeach; ?><?php if(!$bills): ?><tr><td colspan="11" class="text-center text-muted py-4">No vendor bills found.</td></tr><?php endif; ?></tbody></table></div></div>
<?php require_once __DIR__ . '/../includes/re_layout_footer.php'; ?>
